#!/usr/bin/env bash
# vim: ft=bash ts=2 sw=2 sts=2 et :
 
alias ..='cd ..'
alias ...='cd ../../../'

alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias gp="git add *;git commit -am save;git push;git status"
alias grep='grep --color=auto'
alias h="history"
alias ls="ls -G"
alias vi="vim -u $here/etc/dotvimrc "
alias vims="vim +PluginInstall +qall"         

export BASH_SILENCE_DEPRECATION_WARNING=1
export PATH="$PWD:/opt/homebrew/bin:$PATH"
export PYTHONPATH="$here/src:$PYTHONPATH"

# command line tricks
alias ls="ls -G"
alias vi="vim -u $here/etc/dotvimrc "

py()  { python3 $here/src/$1.py $* ; }
ccd() { cd $1; basename `pwd`; }

here() { cd $1; basename `pwd`; }

PROMPT_COMMAND='echo -ne "🚰 ";PS1="$(ccd ..)/$(ccd .):\!\e[m ▶ "'

